CREATE DATABASE COURSE;

USE COURSE;

CREATE TABLE USER (
	IDUSER VARCHAR2(10) PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(20) NOT NULL,
);

CREATE TABLE STUDENT(
	IDUSER VARCHAR2(10) NOT NULL,
	YEAR DATE NOT NULL,
	FOREIGN KEY (IDUSER) REFERENCES USER(IDUSER)
);

CREATE TABLE TEACHER(
	IDUSER VARCHAR2(10) NOT NULL,
	IDCOURSE VARCHAR2(10) NOT NULL,
	FOREIGN KEY (IDUSER) REFERENCES USER(IDUSER)
);

CREATE TABLE ENROLL(
	IDUSER VARCHAR2(10) NOT NULL,
	IDCOURSE VARCHAR2(10) NOT NULL,
	FOREIGN KEY (IDUSER) REFERENCES STUDENT(IDUSER)
);

CREATE TABLE COURSE(
	IDUSER VARCHAR2(10) NOT NULL,
	IDCOURSE VARCHAR2(10) PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	DESCRIPTION VARCHAR2(100) NOT NULL,
	LOCALTION VARCHAR2(20) NOT NULL,
	OPENED VARCHAR2(10) NOT NULL,
	FOREIGN KEY (IDUSER) REFERENCES ENROLL(IDUSER)
);